install.packages("remotes")
install.packages("data.table")
install.packages("stringr")
install.packages("ggplot2")
install.packages("gt")
install.packages("webshot2")
install.packages("dplyr")
install.packages("patchwork")
remotes::install_github("MSKCC-Epi-Bio/bstfun", force = T)
